### ISSUE TITLE
File Development-5d8666050474.json is absent

### ISSUE THREAD

**Issue by micrcx** [shamblett/dartivity#1]
I managed to compile and build a project, but an error occurred during execution:
```
Unhandled exception:
FileSystemException: Cannot open file, path = 'credentials\Development-5d8666050474.json' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:547:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:592:18)
#4      DartivityMessaging.initialise (file:///home/michael_k/.pub-cache/hosted/pub.dartlang.org/dartivity_messaging-1.0.0/lib/src/dartivity_messaging.dart:78:62)
<asynchronous suspension>
#5      Dartivity.initialise (file:///home/michael_k/IdeaProjects/dartivity/lib/dartivity.dart:140:23)
<asynchronous suspension>
#6      main (file:///home/michael_k/IdeaProjects/dartivity/bin/main.dart:30:19)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
Where can I find this file?

**Comment by shamblett** [comment]
This is the credentials file associated with your GCE project, see the GCE docs on how to generate this for pub/sub.  You'll also need to change the name, along with the other GCE project definitions in the dartivity_local_conf.dart file if you have not already done so.

**Comment by micrcx** [comment]
Can you give a link?

**Comment by shamblett** [comment]
Have a look [here](http://googleapis.github.io/google-cloud-ruby/docs/google-cloud-pubsub/master/file.AUTHENTICATION.html)
